# Generated by Django 6.0.2 on 2026-02-12 09:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursecategory",
            name="course_category_centre",
        ),
    ]
