# Generated by Django 6.0.2 on 2026-02-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_remove_coursecategory_course_category_centre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursedetail",
            name="course_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("COMPLETED", "Completed"),
                    ("UPCOMING", "Upcoming"),
                    ("CANCELLED", "Cancelled"),
                    ("HOLD", "Hold"),
                ],
                null=True,
            ),
        ),
    ]
